stryker_dcrg8_monthly_dashboard_vCREATE OR REPLACE VIEW "stryker_dcrg8_monthly_dashboard_v" AS 
SELECT
  (CASE WHEN (device LIKE 'Unit-%') THEN replace(device, 'Unit-', 'MCC-') ELSE device END) device_name
, device
, timestamp
, hour_bucket
, day_bucket
, week_bucket
, month_bucket
, pf_target_setpoint
, eq_voltage
, eq_current
, active_power_total
, reactive_power_total
, voltage_l1
, voltage_l2
, voltage_l3
, current_l1
, current_l2
, current_l3
, active_energy_import_kwh
, reactive_energy_import_kvarh
, apparent_energy_kvah
, active_energy_export_kwh
, reactive_energy_export_kvarh
, frequency_hz
, cap_l1
, cap_l2
, cap_l3
, pf_uncorrected
, pf_delta_to_target
, pf_corrected
, measured_pf
, pf_measured
, pf_uncorrected_calc
, pf_corrected_calc
, pf_improvement
, pf_cost_avoided_monthly
, pf_annualized_savings
, voltage_thd_l1
, voltage_thd_l2
, voltage_thd_l3
, current_thd_l1
, current_thd_l2
, current_thd_l3
, total_pf
, active_power_l1
, active_power_l2
, active_power_l3
, apparent_power_total
, apparent_power_l1
, apparent_power_l2
, apparent_power_l3
, reactive_power_l1
, reactive_power_l2
, reactive_power_l3
, partition_0
, partition_1
, partition_2
, partition_3
, partition_4
, partition_5
FROM
  "dcrg8-data"."stryker_meter_data_devices"
